version: "3.9"

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${DB_NAME:-go-metrics}"
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - ./db/postgresql/:/var/lib/postgresql/data/
      - ./scripts/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
    ports:
      - "5051:5432"
    networks:
      - default

  go-metrics-collector-server:
    image: golang:1.22
    volumes:
      - ./go-metrics-service/go-metrics-collector:/go/src/github.com/AndrXxX/go-metrics-collector/
    working_dir: /go/src/github.com/AndrXxX/go-metrics-collector/
    environment:
      - ADDRESS=:8080
    ports:
      - ${METRICS_SERVER_PORT:-8080}:8080
      - "5555:8080"
    entrypoint: go run github.com/AndrXxX/go-metrics-collector/cmd/server
    depends_on:
      - db

networks:
  default:
    driver: bridge

