version: "3.9"

services:
  db:
    image: postgres:16.3
    container_name: go-metrics-db
    environment:
      - POSTGRES_DB=${DB_NAME:-go_metrics_db}
      - POSTGRES_USER=${DB_USERNAME:-go_metrics_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-go_metrics_pass}
    volumes:
      - ./db/postgresql/:/var/lib/postgresql/data/
    ports:
      - "5051:5432"
    networks:
      - default

  go-metrics-collector-server:
    image: golang:1.22
    container_name: go-metrics-server
    volumes:
      - ./go-metrics-service/go-metrics-collector:/go/src/github.com/AndrXxX/go-metrics-collector/
    working_dir: /go/src/github.com/AndrXxX/go-metrics-collector/
    environment:
      - ADDRESS=:8080
      - DATABASE_DSN=host=go-metrics-db user=${DB_USERNAME:-go_metrics_user} password=${DB_PASSWORD:-go_metrics_pass} dbname=${DB_NAME:-go_metrics_db} sslmode=disable
    ports:
      - ${METRICS_SERVER_PORT:-8080}:8080
    entrypoint: go run github.com/AndrXxX/go-metrics-collector/cmd/server
    depends_on:
      - db

networks:
  default:
    driver: bridge

